### ISSUE TITLE
Bug at start in Windows 7

### ISSUE THREAD

**Issue by pepaulo** [Bible-Projects/believers-sword-app#105]
The app do not start

![image](https://user-images.githubusercontent.com/7110757/190422579-dbf0e799-6dc5-4c89-ae19-d0697d1155ee.png)

**Comment by BroJenuel** [comment]
@pepaulo thanks for making an issue,, Im going to check it now,, for the new update, it has a lot of things changed... can you try uninstalling it and reinstalling again? thanks thanks, beep me up if this fix work.

**Comment by pepaulo** [comment]
@BroJenuel I make this, but the error no fix.

**Comment by BroJenuel** [comment]
ill try to do more testing then,, this might take a while since I have a full-time job so just going to do it on my ... can you do this next fix...

first go to: `C:\Users\<username>\AppData\Roaming` and delete the folder `believers-sword-app` this will reset your believer's sword app. Hope it works.

**Comment by pepaulo** [comment]
Thank you. Now the app start normally. :)
